version: '3'

services:
  config:
    image: config-service
    networks:
      - all
    ports:
      - 8090:8090
    environment:
      ZIPKIN_SERVER: zipkin
  gateway:
    image: gateway-service
    networks:
      - all
    ports:
      - 8080:8080
    environment:
      DISCOVERY_SERVER: discovery
      ZIPKIN_SERVER: zipkin
  discovery:
    image: discovery-service
    networks:
      - all
    ports:
      - 8761:8761
  user-service:
    image: user-service
    ports:
      - 8081:8080
    networks:
      - all
    environment:
      DATABASE_HOST: user-db
      DISCOVERY_SERVER: discovery
      ZIPKIN_SERVER: zipkin
      CONFIG_SERVER: config
    depends_on:
      - user-db
      - config
  product-service:
    image: product-service
    ports:
      - 8082:8080
    networks:
      - all
    environment:
      DATABASE_HOST: product-db
      DISCOVERY_SERVER: discovery
      ZIPKIN_SERVER: zipkin
    depends_on:
      - product-db
  user-db:
    image: postgres
    restart: always
    networks:
      - all
    environment:
      POSTGRES_PASSWORD: postgres
  product-db:
    image: postgres
    restart: always
    networks:
      - all
    environment:
      POSTGRES_PASSWORD: postgres
  zipkin:
    image: openzipkin/zipkin
    networks:
      - all
    ports:
      - 9411:9411

networks:
  all:
    driver: bridge
